### ISSUE TITLE
Fix WordPress VIP warning around *_user_meta() calls

### ISSUE THREAD

**Issue by jamesrwilliams** [jamesrwilliams/flagpole#10]
As we are using PHPCS with WordPress VIP standards, warnings are thrown for using either `get_user_meta()` and `update_user_meta()`. My understanding of this is that currently, WordPress VIP supports `*_user_attribute()` so we should write a wrapper around these meta calls to use `*_user_attribute` first if we're in a VIP enviroment?

See:

- https://vip.wordpress.com/functions/get_user_attribute/
- https://vip.wordpress.com/functions/update_user_attribute/

N.B - This stemmed from reading about how this effected [WPSEO](https://github.com/Yoast/wordpress-seo/issues/7697).

**Comment by jenkoian** [comment]
We are using this plugin in a VIP environment and we actually get PHP notices that `*_user_attribute()` is deprecated (see https://github.com/jenkoian/vip-go-mu-plugins/blob/master/vip-helpers/vip-deprecated.php#L474) and under the hood it just calls `*_user_meta()` anyway, so wondering if we can just use `*_user_meta()`? Happy to submit a PR if you're happy to?

**Comment by jamesrwilliams** [comment]
Thanks for highlighting this, don't currently have a test env for VIP, I'm just using the VIP sniffs. Which without the wrapper produces the following violation:
```
WordPress.VIP.RestrictedFunctions.user_meta_update_user_meta: update_user_meta() usage is highly discouraged, check VIP documentation on "Working with wp_users"
```

Annoyingly I cannot access the documentation which is the rationale behind the current code in [class-flagpole.php#432](https://github.com/jamesrwilliams/flagpole/blob/develop/includes/class-flagpole.php#L432-L449).  

Do you know if the method also deprecated in the regular VIP environment or is it just a VIP Go deprecation (I'm assuming you have access to the VIP documentation)?

**Comment by jenkoian** [comment]
The only documentation I'm aware of is https://vip.wordpress.com/documentation/vip-go/ which I believe is open (I think the docs you refer to are the old WP.com docs but I believe they're being phased out - not 100% on that though). In fact I just found the old docs (on the lobby so yes restricted) and they link to this page on the new docs: https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/

With regards the deprecations in question, this is where the user attribute method gets flagged up https://github.com/Automattic/vip-go-mu-plugins/blob/master/vip-helpers/vip-deprecated.php#L460-L483 and you can see if recommends `get_user_meta` 

I think generally although the *_user_meta() functions are discouraged they are favourable over `*_user_attribute()` on the new platform at least. However, I appreciate you may want to support both, so up to you how you want to handle this I guess.

**Comment by jenkoian** [comment]
Any update on this, we're still getting errors on this on VIP, would be neat to fix somehow. Is there a neat way of supporting both?

**Comment by jamesrwilliams** [comment]
Just tagged the release of [0.1.2-beta](https://github.com/jamesrwilliams/flagpole/releases/tag/0.1.2-beta) which has @strayobject 's PR merged in. Hopefully this fixes the VIP issues we've been seeing.

**Comment by jamesrwilliams** [comment]
When you get an opportunity @jenkoian, can you let me know if that latest release has fixed the VIP issues you where experiencing

**Comment by jenkoian** [comment]
Hey yeah works sweet, one thing we may want to do is change the constant being checked to `WPCOM_IS_VIP_ENV` which is what [this plugin](https://github.com/trewknowledge/GDPR/commit/dcf23e9337bced2c694378486beb04f1c252eef8) has used and probably makes a bit more semantic sense

**Comment by jamesrwilliams** [comment]
Hey @jenkoian the constant has been updated to `WPCOM_IS_VIP_ENV` as you suggested as of 3a6f5b9. Will be updating the release shortly to include this and some other minor changes. 

I've updated docs reference to https://automattic.github.io/vip-go-mu-plugins/#constant_WPCOM_IS_VIP_ENV
