### ISSUE TITLE
Consider renaming `is_enabled()` function

### ISSUE THREAD

**Issue by peterhartree** [jamesrwilliams/flagpole#15]
I think `is_enabled()` is a slightly too generic as a function name.

- If another developer sees this function but doesn't know we're using feature flags, it's not immediately obvious what the function does.
- The name is generic enough that there's a reasonable chance of conflict with other functions with the same name.

I'd probably vote for maximal clarity: `feature_flag_enabled()` or `is_feature_flag_enabled()`.

**Comment by jamesrwilliams** [comment]
I've picked up work on this again. The function at the moment is called `flagpole_flag_enabled` out of the box which I think is nice and specific enough. If it's too long or if people think it's unwieldy, they can always alias it.
