### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by jenkoian** [jamesrwilliams/flagpole#28]
Are you able to tag a new stable release? Or a `0.x` if not willing to commit to `1.x`+?

**Comment by jamesrwilliams** [comment]
Hi @jenkoian, I've tagged v0.1.0-beta as a stable release.

https://github.com/jamesrwilliams/flagpole/releases/tag/0.1.0-beta

There have been breaking changes to the API  mainly the function names you use to register and check flags but I don't see these changing anytime soon:
