### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by jenkoian** [jamesrwilliams/flagpole#31]
Please can you tag a new release since https://github.com/jamesrwilliams/flagpole/pull/30 was merged.

The reason behind this is we have new relic alerts set up and currently they're constantly firing due to the PHP warning from this plugin. We therefore want to upgrade it to include this fix. 

Thanks!

**Comment by jamesrwilliams** [comment]
Hello @jenkoian sorry for the sluggish response time (started a new job) but I've just tagged [v0.1.1](https://github.com/jamesrwilliams/flagpole/releases/tag/0.1.1-beta) including your work on #30.

**Comment by jenkoian** [comment]
Thanks!
