### ISSUE TITLE
Document the flag groups and querystring feature

### ISSUE THREAD

**Issue by peterhartree** [jamesrwilliams/flagpole#32]
The flag group and querystring enable feature is great. If you're intending to keep it, please add to the README.

**Comment by jamesrwilliams** [comment]
Started work on this here [feat/query-string-docs](https://github.com/jamesrwilliams/flagpole/tree/feat/query-string-docs) which is quickly turning into a re-write of all the docs, which I don't think is a bad thing.

**Comment by jamesrwilliams** [comment]
Documentation has been merged into our development branch as of fbd6d6d.
